/**
 * Entry browser-safe de `@editor-video/core`.
 * Usado pela condition "browser" do package.json — sem Node (fs/path/stream).
 */
export { PILLARS, WEEKDAY_CATEGORIES, findPillar, type Pillar } from './christian.js';
export {
  RABISCO_CHARACTER_NAME,
  RABISCO_TAGLINE,
  RABISCO_EXPRESSIONS,
  RABISCO_ACTIONS,
  resolveRabiscoAsset,
} from './rabisco.js';
export {
  COUNTDOWN_DURATION_FRAMES,
  INTRO_DURATION_FRAMES,
  OUTRO_DURATION_FRAMES,
  christianDurationInFrames,
  curiosidadeDurationInFrames,
  rabiscoDurationInFrames,
  totalDurationInFrames,
  type AmbientAudioLayer,
  type AmbientAudioTimeline,
  type AmbientConcept,
  type AmbientLayerType,
  type AmbientPurpose,
  type AmbientSoundEvent,
  type AmbientVisualTimeline,
  type CaptionSegment,
  type CaptionWord,
  type CharacterState,
  type ChristianProps,
  type ChristianScene,
  type CuriosidadeProps,
  type CuriosidadeScene,
  type ProjectKindValue,
  type ProjectStatusValue,
  type RabiscoAction,
  type RabiscoAnimation,
  type RabiscoEmotion,
  type RabiscoPosition,
  type RabiscoProps,
  type RabiscoScene,
  type RenderClip,
  type TopListProps,
} from './types.js';
export {
  MIDNIGHT_BRAND,
  MIDNIGHT_TAGLINE,
  MIDNIGHT_SERIES_ID,
  MIDNIGHT_PIPELINE_VERSION,
  MIDNIGHT_RECIPE_VERSION,
  MIDNIGHT_PLAYLISTS,
  MIDNIGHT_UNIVERSES,
  MIDNIGHT_RECIPES,
  LEGACY_PRESET_TO_RECIPE,
  getMidnightRecipe,
  getMidnightVariation,
  resolveLayerVolumes,
  resolveEvents,
  formatDurationLabel,
  buildMidnightTitle,
  buildShortsTitle,
  defaultDurationsForPillar,
  recipesForUniverse,
  type MidnightUniverse,
  type MidnightPillar,
  type MidnightPlaylistKey,
  type MidnightVariationId,
  type MidnightRecipeDefinition,
  type MidnightVariation,
  type MidnightRecipeEvent,
  type MidnightRecipeId,
} from './midnight.js';
